/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package merge;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class MergeSortTest
{
  @Test
  void testMergeSort()
  {
    int[] arr = {8, 4, 23, 42, 16, 15};
    int[] expected = {4, 8, 15, 16, 23, 42};
    MergeSort.mergeSort(arr);
    assertArrayEquals(expected, arr);
  }

  @Test
  void testMergeSortWithUniqueData()
  {
    int[] fewUniques = {5, 12, 7, 5, 5, 7};
    int[] expected = {5, 5, 5, 7, 7, 12};
    MergeSort.mergeSort(fewUniques);
    assertArrayEquals(expected, fewUniques);

    int[] nearlySorted = {2, 3, 5, 7, 13, 11};
    int[] expected2 = {2, 3, 5, 7, 11, 13};
    MergeSort.mergeSort(nearlySorted);
    assertArrayEquals(expected2, nearlySorted);

    int[] reverseSorted = {20, 18, 12, 8, 5, -2};
    int[] expected3 = {-2, 5, 8, 12, 18, 20};
    MergeSort.mergeSort(reverseSorted);
    assertArrayEquals(expected3, reverseSorted);


  }
}
