/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tree;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class TreeTest
{

  @Test
  public void testTreeInstantiation()
  {
    BinaryTree<Integer> binaryTree = new BinaryTree<>();

    assertNull(binaryTree.getRoot());
  }

  @Test public void testPreOrderTraversal()
  {

  }

  @Test public void testInOrderTraversal()
  {

  }

  @Test public void testPostOrderTraversal()
  {

  }


}
