/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package graphs;

import org.junit.jupiter.api.Test;

import java.util.LinkedList;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

class GraphTest
{
  @Test
  public void testGraphCanAddVertex()
  {
    Graph<Integer> graph = new Graph<>(5);
    Vertex<Integer> vertex = graph.addVertex(89);
    assertEquals(89, vertex.value);
  }

  @Test
  public void testGraphCanAddEdge()
  {
    Graph<Character> graph = new Graph<>(5);
    Vertex<Character> vertexA = graph.addVertex('!');
    Vertex<Character> vertexB = graph.addVertex(';');
    graph.addEdge(vertexA, vertexB);
    assertEquals(1, graph.getNeighbors(vertexA).size());
    assertEquals(0, graph.getNeighbors(vertexB).size());
  }

  @Test
  public void testGraphCanAddEdgeWithWeight()
  {
    Graph<String> graph = new Graph<>(5);
    Vertex<String> vertexA = graph.addVertex("52nd Street");
    Vertex<String> vertexB = graph.addVertex("35th Street");
    graph.addEdge(vertexA, vertexB, 5);
    assertEquals(5, graph.getNeighbors(vertexA).get(0).weight);
  }

  @Test
  public void testGraphCanGetVertices()
  {
    Graph<Double> graph = new Graph<>(5);
    Vertex<Double> vertexA = graph.addVertex(67.05);
    Vertex<Double> vertexB = graph.addVertex(35.05);

    LinkedList<Vertex<Double>> vertices = graph.getVertices();

    assertEquals(2, vertices.size());
  }

  @Test
  public void testGraphHasAccurateSize()
  {
    Graph<String> graph = new Graph<>(5);
    Vertex<String> vertexA = graph.addVertex("Apples");
    Vertex<String> vertexB = graph.addVertex("Bananas");
    assertEquals(2, graph.size());
  }
}
