/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linked.list;

public class LinkedList
{
  private Node head;

  public Node getHead() {
    return head;
  }

  public void insert(int value)
  {
    Node newNode = new Node(value);
    newNode.setNext(head);

    head = newNode;
  }

  public boolean includes(int value)
  {
    Node current = head;

    while (current != null)
    {
      if (current.getValue() == value)
      {
        return true;
      }
      current = current.getNext();
    }

    return false;
  }

  @Override
  public String toString()
  {
    String values = "";

    Node current = head;

    while (current != null)
    {
      values += "{ " + current.getValue() + " } -> ";
      current = current.getNext();
    }

    values += "NULL";

    return values;
  }
}
