/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linked.list;

public class LinkedList<T>
{
  private Node<T> head;

  public Node<T> getHead()
  {
    return head;
  }

  public void append(T value)
  {
    Node<T> current = head;

    if (current == null)
    {
      head = new Node<>(value);
      return;
    }

    while (current.getNext() != null)
    {
      current = current.getNext();
    }

    current.setNext(new Node<>(value));


  }

  public void insertBefore(T value, T newValue)
  {

  }

  public void insertAfter(T value, T newValue)
  {

  }

  public void insert(T value)
  {
    Node<T> newNode = new Node<>(value);
    newNode.setNext(head);

    head = newNode;
  }

  public boolean includes(int value)
  {
    Node<T> current = head;

    while (current != null)
    {
      if (current.getValue().equals(value))
      {
        return true;
      }
      current = current.getNext();
    }

    return false;
  }

  @Override
  public String toString()
  {
    String values = "";

    Node<T> current = head;

    while (current != null)
    {
      values += "{ " + current.getValue() + " } -> ";
      current = current.getNext();
    }

    values += "NULL";

    return values;
  }
}
