/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package insertion;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class InsertionSortTest
{
  @Test
  public void testInsertionSort()
  {
    int[] testData = {8, 4, 23, 42, 16, 15};

    InsertionSort.insertionSort(testData);

    assertArrayEquals(testData, new int[]{4, 8, 15, 16, 23, 42});
  }

  @Test
  public void testInsertionSortWithUniqueData()
  {
    int[] reversedSorted = {20, 18, 12, 8, 5, -2};
    int[] fewUniques = {5, 12, 7, 5, 5, 7};
    int[] nearlySorted = {2, 3, 5, 7, 13, 11};

    InsertionSort.insertionSort(reversedSorted);
    InsertionSort.insertionSort(fewUniques);
    InsertionSort.insertionSort(nearlySorted);

    assertArrayEquals(reversedSorted, new int[]{-2, 5, 8, 12, 18, 20});
    assertArrayEquals(fewUniques, new int[]{5, 5, 5, 7, 7, 12});
    assertArrayEquals(nearlySorted, new int[]{2, 3, 5, 7, 11, 13});
  }
}
