/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linked.list;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LinkedListTest {
    @Test void canInstantiateLinkedList()
    {
      LinkedList linkedList = new LinkedList();

      assertEquals("NULL", linkedList.toString());
    }

    @Test void canInsertIntoLinkedList()
    {
      LinkedList linkedList = new LinkedList();

      linkedList.insert(5);

      assertTrue(linkedList.toString().contains("5"));
    }

    @Test void headPointsToFirst()
    {
      LinkedList linkedList = new LinkedList();

      linkedList.insert(3);

      assertEquals(3, linkedList.getHead().getValue());
    }

    @Test void canInsertMultipleNodes()
    {
      LinkedList linkedList = new LinkedList();

      linkedList.insert(5);
      linkedList.insert(2);
      linkedList.insert(-1);

      assertTrue(linkedList.toString().contains("5"));
      assertTrue(linkedList.toString().contains("2"));
      assertTrue(linkedList.toString().contains("-1"));
    }

    @Test void includesReturnsTrue()
    {
      LinkedList linkedList = new LinkedList();

      linkedList.insert(10);

      assertTrue(linkedList.includes(10));

    }

    @Test void includesReturnsFalse()
    {
      LinkedList linkedList = new LinkedList();

      linkedList.insert(53);

      assertFalse(linkedList.includes(12));
    }

    @Test void toStringReturnsFormattedText()
    {
      LinkedList linkedList = new LinkedList();

      linkedList.insert(12);
      linkedList.insert(5);
      linkedList.insert(3);
      linkedList.insert(7);
      linkedList.insert(9);

      String shouldEqual = "{ 9 } -> { 7 } -> { 3 } -> { 5 } -> { 12 } -> NULL";
      String s = linkedList.toString();
      assertTrue(linkedList.toString().equals(shouldEqual));
    }

}
